import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Shield, Send, Eye, Users, Ban, VolumeX } from "lucide-react";
import { toast } from "sonner";
import { SignedShell } from "@/components/signed-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useMe } from "@/hooks/use-me";
import { getModerationOverview, listFounders, setUserRole, moderateUser, getUserSecurityInfo, revealUserEmail, createGlobalAnnouncement } from "@/lib/nyxoshi/server";

export const Route=createFileRoute("/founders")({component:FoundersPage});
function FoundersPage(){return <SignedShell><Inner/></SignedShell>}
function Inner(){const {me}=useMe();const qc=useQueryClient();const overview=useQuery({queryKey:["moderation-overview"],queryFn:()=>getModerationOverview(),enabled:me?.role==="founder"||me?.role==="admin"||me?.role==="moderator"});const founders=useQuery({queryKey:["founders"],queryFn:()=>listFounders(),enabled:me?.role==="founder"});const security=useQuery({queryKey:["founder-security"],queryFn:()=>getUserSecurityInfo(),enabled:me?.founderNumber===1});const [announcement,setAnnouncement]=useState("");const [reason,setReason]=useState("");const [email,setEmail]=useState<string|null>(null);
 async function role(targetUserId:string,role:any){try{await setUserRole({data:{targetUserId,role}});await qc.invalidateQueries({queryKey:["moderation-overview"]});await qc.invalidateQueries({queryKey:["founders"]});toast.success("Cargo atualizado.")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível atualizar.")}}
 async function reveal(targetUserId:string){try{const r=await revealUserEmail({data:{targetUserId,reason}});setEmail(r.email);setReason("")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível revelar o e-mail.")}}
 async function sendAnnouncement(){if(!announcement.trim())return;try{await createGlobalAnnouncement({data:{body:announcement,seconds:12}});setAnnouncement("");toast.success("Comunicado enviado para todo o Nyxoshi.")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível enviar.")}}
 if(!me||me.role!=="founder"&&me.role!=="admin"&&me.role!=="moderator")return <p className="p-8 text-center text-muted">Acesso negado.</p>;
 return <div className="p-4 pb-12"><header className="border-b border-border pb-4"><h1 className="font-display text-2xl">Painel dos Fundadores</h1><p className="mt-1 text-sm text-muted">Permissões administrativas verificadas no servidor.</p></header>
 {me.role==="founder"?<section className="mt-5 nyx-panel rounded-2xl p-4"><div className="flex items-center gap-2"><Shield className="text-fuchsia-300"/><h2 className="font-medium">Fundadores</h2></div><div className="mt-3 space-y-2">{founders.data?.map((f:any)=><div key={f.user_id} className="flex items-center justify-between rounded-xl border border-border p-3"><div><strong>{f.display_name}</strong><p className="text-xs text-muted">@{f.username} · Fundador #{f.founder_number??"—"}</p></div>{me.founderNumber===1&&f.user_id!==me.userId?<div className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>void role(f.user_id,"admin")}>Admin</Button><Button size="sm" variant="ghost" onClick={()=>void role(f.user_id,"user")}>Remover</Button></div>:null}</div>)}</div></section>:null}
 {me.founderNumber===1?<><section className="mt-5 nyx-panel rounded-2xl p-4"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Eye className="text-fuchsia-300"/><h2 className="font-medium">Segurança confidencial — Fundadora #1</h2></div><Button asChild size="sm" variant="outline"><Link to="/founder-security">Abrir painel separado</Link></Button></div><p className="mt-1 text-xs text-muted">Somente a Fundadora #1 pode acessar e revelar e-mails.</p><div className="mt-3 space-y-2">{security.data?.map((u:any)=><div key={u.user_id} className="rounded-xl border border-border p-3"><div className="flex items-center justify-between gap-3"><div><strong>{u.display_name}</strong><p className="text-xs text-muted">@{u.username} · {u.emailMasked}</p></div><Button size="sm" variant="outline" onClick={()=>void reveal(u.user_id)}>Ver e-mail</Button></div></div>)}</div>{email?<div className="mt-3 rounded-xl border border-fuchsia-400/30 bg-fuchsia-500/10 p-3 text-sm">E-mail revelado: <strong>{email}</strong></div>:null}{!email?null:<Button className="mt-2" variant="ghost" onClick={()=>setEmail(null)}>Ocultar</Button>}<Input className="mt-3" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo para acessar o e-mail (mínimo 8 caracteres)"/></section>
 <section className="mt-5 nyx-panel rounded-2xl p-4"><div className="flex items-center gap-2"><Send className="text-fuchsia-300"/><h2 className="font-medium">Comunicado global</h2></div><p className="mt-1 text-xs text-muted">Mensagem do Nyxoshi enviada pelo grupo dos Fundadores e exibida para todos.</p><Textarea className="mt-3" value={announcement} onChange={e=>setAnnouncement(e.target.value)} placeholder="Mensagem do Nyxoshi..." maxLength={500}/><Button className="mt-2" onClick={()=>void sendAnnouncement()}><Send/>Enviar</Button></section></>:null}
 <section className="mt-5 nyx-panel rounded-2xl p-4"><div className="flex items-center gap-2"><Users className="text-fuchsia-300"/><h2 className="font-medium">Visão geral</h2></div><p className="mt-2 text-sm text-muted">Usuários: {overview.data?.counts.users??0} · Posts: {overview.data?.counts.posts??0} · Denúncias: {overview.data?.counts.reports??0}</p></section></div>}
