import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, MessageCircle, Search, ShieldAlert, X, Users, Heart, Reply, Flag, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { SignedShell } from "@/components/signed-shell";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { UserAvatar } from "@/components/user-avatar";
import { searchNyxoshi, listConversations, listMessageRequests, decideMessageRequest, sendMessage, listMessages, getMessageThreadForUser, toggleMessageReaction, deleteMessage, createReport, createGroup, listGroups, listGroupMessages, sendGroupMessage, toggleGroupMessageReaction, deleteGroupMessage, createGlobalAnnouncement } from "@/lib/nyxoshi/server";
import { useMe } from "@/hooks/use-me";

export const Route = createFileRoute("/messages")({ component: MessagesPage });
type Conversation = { threadId:string; other:{userId:string;username:string;displayName:string;image:string|null}; lastMessage:{body:string;createdAt:string;senderId:string}|null; unread:number };
type SearchPerson = {userId:string;username:string;displayName:string;image:string|null};
function MessagesPage(){return <SignedShell><MessagesInner/></SignedShell>}
function MessagesInner(){
 const {me}=useMe(); const qc=useQueryClient(); const [tab,setTab]=useState<"conversations"|"groups"|"requests"|"spam">("conversations");
 const [selected,setSelected]=useState<Conversation|null>(null); const [selectedGroup,setSelectedGroup]=useState<{id:string;name:string}|null>(null); const [q,setQ]=useState(""); const [groupName,setGroupName]=useState(""); const [groupMembers,setGroupMembers]=useState<string[]>([]);
 const conversations=useQuery({queryKey:["conversations"],queryFn:()=>listConversations(),enabled:Boolean(me)}); const groups=useQuery({queryKey:["groups"],queryFn:()=>listGroups(),enabled:Boolean(me)}); const requests=useQuery({queryKey:["message-requests"],queryFn:()=>listMessageRequests(),enabled:Boolean(me)}); const search=useQuery({queryKey:["message-user-search",q],queryFn:()=>searchNyxoshi({data:{q}}),enabled:q.trim().length>=2});
 async function decide(id:string,a:"accept"|"decline"|"spam"){try{await decideMessageRequest({data:{requestId:id,action:a}});await qc.invalidateQueries({queryKey:["message-requests"]});await qc.invalidateQueries({queryKey:["conversations"]});toast.success("AÃ§Ã£o concluÃ­da.")}catch(e){toast.error(e instanceof Error?e.message:"NÃ£o foi possÃ­vel concluir.")}}
 async function create(){if(!groupName.trim()||groupMembers.length<1)return;try{await createGroup({data:{name:groupName,memberIds:groupMembers}});setGroupName("");setGroupMembers([]);await qc.invalidateQueries({queryKey:["groups"]});toast.success("Grupo criado.")}catch(e){toast.error(e instanceof Error?e.message:"NÃ£o foi possÃ­vel criar o grupo.")}}
 return <div className="min-h-dvh"><header className="sticky top-0 z-20 border-b border-border bg-bg/90 px-4 py-3 backdrop-blur-sm"><h1 className="font-display text-xl">Mensagens</h1><div className="relative mt-3"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar pessoas..." className="rounded-full bg-secondary pl-9"/></div><div className="mt-3 grid grid-cols-4 rounded-xl border border-border p-1 text-xs">{(["conversations","groups","requests","spam"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-lg px-2 py-2 ${tab===t?"bg-secondary text-fg":"text-muted"}`}>{t==="conversations"?"Conversas":t==="groups"?"Grupos":t==="requests"?`SolicitaÃ§Ãµes (${requests.data?.filter(r=>r.status==='pending').length??0})`:"Spam"}</button>)}</div></header>
 {q.trim().length>=2&&search.data?.people.length?<section className="border-b border-border p-4"><p className="text-xs text-muted">Pessoas</p>{search.data.people.map((p:SearchPerson)=><div key={p.userId} className="mt-2 flex items-center gap-2"><button className="flex min-w-0 flex-1 items-center gap-3 text-left" onClick={async()=>{const id=await getMessageThreadForUser({data:p.userId});setSelected({threadId:id??"",other:p,lastMessage:null,unread:0});setSelectedGroup(null);setTab("conversations")}}><UserAvatar username={p.username} displayName={p.displayName} image={p.image} toProfile={false}/><span><strong>{p.displayName}</strong><span className="block text-xs text-muted">@{p.username}</span></span></button>{tab==="groups"?<button className="rounded-lg border px-2 py-1 text-xs" onClick={()=>setGroupMembers(v=>v.includes(p.userId)?v.filter(x=>x!==p.userId):[...v,p.userId])}>{groupMembers.includes(p.userId)?"Selecionado":"Adicionar"}</button>:null}</div>)}</section>:null}
 {tab==="groups"?<div className="p-4"><div className="nyx-panel rounded-2xl p-4"><h2 className="font-medium">Criar grupo</h2><Input className="mt-3" value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Nome do grupo"/><p className="mt-2 text-xs text-muted">Selecionados: {groupMembers.length}</p><Button className="mt-3 w-full" onClick={()=>void create()} disabled={!groupName.trim()||!groupMembers.length}><Users className="size-4"/>Criar grupo</Button></div><div className="mt-4 space-y-2">{groups.data?.map(g=><button key={g.id} className="flex w-full items-center gap-3 rounded-xl border border-border p-3 text-left" onClick={()=>{setSelectedGroup(g);setSelected(null)}}><Users className="size-5"/>{g.name}</button>)}</div></div>:tab!=="conversations"?<div className="space-y-3 p-4">{requests.data?.filter(r=>tab==="spam"?r.status==="spam":r.status==="pending").map(r=><div key={r.id} className="nyx-panel rounded-2xl p-4"><div className="flex items-center gap-3"><UserAvatar username={r.sender.username} displayName={r.sender.displayName} image={r.sender.image} toProfile={false}/><strong>{r.sender.displayName}</strong></div><p className="mt-3 text-sm">{r.body}</p>{tab==="requests"?<div className="mt-3 flex gap-2"><Button size="sm" onClick={()=>void decide(r.id,"accept")}><Check/>Aceitar</Button><Button size="sm" variant="outline" onClick={()=>void decide(r.id,"decline")}><X/>Recusar</Button><Button size="sm" variant="ghost" onClick={()=>void decide(r.id,"spam")}><ShieldAlert/>Spam</Button></div>:null}</div>)}</div>:<div className="space-y-2 p-4">{conversations.data?.map(c=><button key={c.threadId} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-secondary" onClick={()=>{setSelected(c);setSelectedGroup(null)}}><UserAvatar username={c.other.username} displayName={c.other.displayName} image={c.other.image} toProfile={false}/><span className="min-w-0 flex-1"><strong className="block truncate">{c.other.displayName}</strong><span className="block truncate text-sm text-muted">{c.lastMessage?.body??"Conversa iniciada"}</span></span></button>)}</div>}
 {selected?<ConversationPanel selected={selected} meId={me?.userId??""}/>:null}{selectedGroup?<GroupPanel group={selectedGroup} meId={me?.userId??""} isFounder={me?.role==="founder"}/>:null}</div>
}
function ConversationPanel({selected,meId}:{selected:Conversation;meId:string}){const query=useQuery({queryKey:["messages",selected.threadId],queryFn:()=>listMessages({data:selected.threadId}),enabled:Boolean(selected.threadId)});const [body,setBody]=useState("");const [reply,setReply]=useState<string|null>(null);const [hold,setHold]=useState<string|null>(null);const msgs=query.data??[];async function send(){if(!body.trim())return;try{const r=await sendMessage({data:{recipientId:selected.other.userId,body,replyToId:reply}});setBody("");setReply(null);if(r.kind==="message"){await query.refetch();}toast.success("Mensagem enviada.")}catch(e){toast.error(e instanceof Error?e.message:"NÃ£o foi possÃ­vel enviar.")}}
 return <div className="fixed inset-0 z-40 flex flex-col bg-bg md:absolute md:inset-auto md:right-4 md:top-24 md:h-[70vh] md:w-[min(440px,calc(100vw-2rem))] md:rounded-2xl md:border md:border-border md:shadow-2xl"><div className="flex items-center gap-3 border-b border-border p-4"><UserAvatar username={selected.other.username} displayName={selected.other.displayName} image={selected.other.image} toProfile={false}/><strong>{selected.other.displayName}</strong></div><div className="flex-1 space-y-2 overflow-y-auto p-4">{msgs.map(m=><div key={m.id} className={`flex ${m.senderId===meId?"justify-end":"justify-start"}`} onDoubleClick={()=>void toggleMessageReaction({data:{messageId:m.id,reaction:"â¤ï¸"}}).then(()=>query.refetch())} onContextMenu={e=>{e.preventDefault();setHold(m.id)}} onPointerDown={()=>window.setTimeout(()=>setHold(m.id),550)}><div className="max-w-[82%]"><div className="rounded-2xl bg-secondary px-3 py-2 text-sm">{m.replyToId?<div className="mb-1 rounded-lg border-l-2 border-fuchsia-400 px-2 text-xs text-muted">Respondendo a uma mensagem</div>:null}{m.body}</div>{m.reactions?.length?<div className="mt-1 flex flex-wrap gap-1">{m.reactions.map((r:any)=><button key={r.reaction} className="rounded-full border px-2 py-0.5 text-xs" onClick={()=>void toggleMessageReaction({data:{messageId:m.id,reaction:r.reaction}}).then(()=>query.refetch())}>{r.reaction} {r.count}</button>)}</div>:null}<div className="mt-1 flex gap-2 text-xs text-muted"><button onClick={()=>void toggleMessageReaction({data:{messageId:m.id,reaction:"â¤ï¸"}}).then(()=>query.refetch())}><Heart className="inline size-3"/></button><button onClick={()=>setReply(m.id)}><Reply className="inline size-3"/></button>{m.senderId===meId?<button onClick={()=>void deleteMessage({data:m.id}).then(()=>query.refetch())}><Trash2 className="inline size-3"/></button>:null}<button onClick={()=>{const reason=window.prompt("Motivo da denÃºncia");if(reason)void createReport({data:{targetMessageId:m.id,reason}}).then(()=>toast.success("Mensagem denunciada."))}}><Flag className="inline size-3"/></button></div>{hold===m.id?<div className="mt-1 rounded-lg border bg-bg p-2 text-xs">AÃ§Ãµes disponÃ­veis: reagir, responder, denunciar e apagar sua mensagem.</div>:null}</div></div>)}</div><div className="border-t border-border p-3">{reply?<div className="mb-2 flex items-center justify-between rounded-lg bg-secondary px-3 py-2 text-xs">Respondendo a uma mensagem<button onClick={()=>setReply(null)}><X className="size-4"/></button></div>:null}<Textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Escreva uma mensagem..."/><Button className="mt-2 w-full" onClick={()=>void send()}>Enviar</Button></div></div>}
function GroupPanel({group,meId,isFounder}:{group:{id:string;name:string};meId:string;isFounder:boolean}){const q=useQuery({queryKey:["group-messages",group.id],queryFn:()=>listGroupMessages({data:group.id})});const [body,setBody]=useState("");const [reply,setReply]=useState<string|null>(null);const [announcement,setAnnouncement]=useState("");const msgs=q.data??[];return <div className="fixed inset-0 z-40 flex flex-col bg-bg md:absolute md:inset-auto md:right-4 md:top-24 md:h-[70vh] md:w-[min(440px,calc(100vw-2rem))] md:rounded-2xl md:border md:border-border md:shadow-2xl"><div className="border-b border-border p-4"><strong>{group.name}</strong><p className="text-xs text-muted">Grupo</p>{group.name==="Fundadores"&&isFounder?<div className="mt-3 rounded-xl border border-fuchsia-400/20 p-3"><p className="text-xs font-medium text-fuchsia-200">Mensagem do Nyxoshi</p><Textarea className="mt-2" value={announcement} onChange={e=>setAnnouncement(e.target.value)} placeholder="Mensagem que aparecerÃ¡ para todos..." maxLength={500}/><Button className="mt-2 w-full" size="sm" onClick={async()=>{if(!announcement.trim())return;try{await createGlobalAnnouncement({data:{body:announcement,seconds:12}});setAnnouncement("");toast.success("Comunicado enviado.")}catch(e){toast.error(e instanceof Error?e.message:"NÃ£o foi possÃ­vel enviar.")}}}><MessageCircle className="size-4"/>Enviar para todo o Nyxoshi</Button></div>:null}</div><div className="flex-1 space-y-2 overflow-y-auto p-4">{msgs.map((m:any)=><div key={m.id} className={`flex ${m.sender_id===meId?"justify-end":"justify-start"}`} onDoubleClick={()=>void toggleGroupMessageReaction({data:{messageId:m.id,reaction:"â¤ï¸"}}).then(()=>q.refetch())}><div className="max-w-[82%] rounded-2xl bg-secondary px-3 py-2 text-sm"><p>{m.body}</p>{m.reactions?.length?<div className="mt-1 text-xs">{m.reactions.map((r:any)=><span key={r.reaction} className="mr-1 rounded-full border px-1">{r.reaction} {r.count}</span>)}</div>:null}<div className="mt-1 flex gap-2 text-xs text-muted"><button onClick={()=>setReply(m.id)}><Reply className="inline size-3"/></button>{m.sender_id===meId?<button onClick={()=>void deleteGroupMessage({data:m.id}).then(()=>q.refetch())}><Trash2 className="inline size-3"/></button>:null}<button onClick={()=>void toggleGroupMessageReaction({data:{messageId:m.id,reaction:"â¤ï¸"}}).then(()=>q.refetch())}><Heart className="inline size-3"/></button></div></div></div>)}</div><div className="border-t border-border p-3">{reply?<div className="mb-2 text-xs text-muted">Respondendo a uma mensagem <button onClick={()=>setReply(null)}>cancelar</button></div>:null}<Textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Mensagem no grupo..."/><Button className="mt-2 w-full" onClick={async()=>{if(!body.trim())return;await sendGroupMessage({data:{groupId:group.id,body,replyToId:reply}});setBody("");setReply(null);void q.refetch()}}>Enviar</Button></div></div>}

